/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import controller.LoginController;
import javax.swing.JOptionPane;
import java.sql.*;
import model.CurrentUser;
import model.Database;
import model.Kru;
import model.Pengguna;


/**
 *
 * @author LENOVO
 */
public class Login extends javax.swing.JFrame {
    private LoginController controller;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        LoginController loginController = new LoginController(); // Inisialisasi controller
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelputih = new javax.swing.JPanel();
        panelhijau = new javax.swing.JPanel();
        btExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        judullogin = new javax.swing.JLabel();
        jtxUsername = new javax.swing.JTextField();
        jtxPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        labelusername = new javax.swing.JLabel();
        labelpassword = new javax.swing.JLabel();
        belumpunyakun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelputih.setBackground(new java.awt.Color(255, 255, 255));
        panelputih.setToolTipText("");

        panelhijau.setBackground(new java.awt.Color(80, 200, 120));

        btExit.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("EXIT");
        btExit.setMaximumSize(new java.awt.Dimension(541, 500));
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExitMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon recycle.png"))); // NOI18N

        javax.swing.GroupLayout panelhijauLayout = new javax.swing.GroupLayout(panelhijau);
        panelhijau.setLayout(panelhijauLayout);
        panelhijauLayout.setHorizontalGroup(
            panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhijauLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhijauLayout.createSequentialGroup()
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhijauLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))))
        );
        panelhijauLayout.setVerticalGroup(
            panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhijauLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        judullogin.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        judullogin.setText("LOGIN");

        jtxUsername.setToolTipText("");
        jtxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxUsernameActionPerformed(evt);
            }
        });

        btLogin.setBackground(new java.awt.Color(80, 200, 120));
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btLogin.setBorderPainted(false);
        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLoginMouseClicked(evt);
            }
        });
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        labelusername.setText("Username");

        labelpassword.setText("Password");

        belumpunyakun.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        belumpunyakun.setForeground(new java.awt.Color(102, 153, 255));
        belumpunyakun.setText("Belum punya akun? ");
        belumpunyakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                belumpunyakunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelputihLayout = new javax.swing.GroupLayout(panelputih);
        panelputih.setLayout(panelputihLayout);
        panelputihLayout.setHorizontalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelputihLayout.createSequentialGroup()
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelputihLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelusername)
                            .addComponent(labelpassword)))
                    .addGroup(panelputihLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(judullogin))
                    .addGroup(panelputihLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(belumpunyakun)
                            .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(panelhijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelputihLayout.setVerticalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelputihLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(judullogin)
                .addGap(25, 25, 25)
                .addComponent(labelusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(belumpunyakun, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(panelhijau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelputih, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseClicked
        dispose();
    }//GEN-LAST:event_btExitMouseClicked

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
                                                                                  
    // Ambil input username dan password dari form
    String username = jtxUsername.getText();
    String password = new String(jtxPassword.getPassword());

    // Validasi input kosong
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username atau Password tidak boleh kosong.", "Login Gagal", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Autentikasi menggunakan LoginController
        LoginController loginController = new LoginController();
        boolean isAuthenticated = loginController.login(username, password);

        if (isAuthenticated) {
            // Login berhasil
            JOptionPane.showMessageDialog(this, "Login berhasil!", "Login Berhasil", JOptionPane.INFORMATION_MESSAGE);

            // Ambil pengguna yang sedang login
            Object currentUser = CurrentUser.getInstance();

            if (currentUser instanceof Kru) {
                // Navigasi ke MenuKruLihatData jika user adalah Kru
                MenuKruLihatData menuKru = new MenuKruLihatData();
                menuKru.setVisible(true);
            } else if (currentUser instanceof Pengguna) {
                // Navigasi ke MenuUserRequest jika user adalah Pengguna
                MenuUserRequest menuPengguna = new MenuUserRequest();
                menuPengguna.setVisible(true);
            }

            // Tutup form login
            this.dispose();
        } else {
            // Login gagal
            JOptionPane.showMessageDialog(this, "Username atau Password salah.", "Login Gagal", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat login: " + e.getMessage(), "Login Gagal", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btLoginActionPerformed

    private void belumpunyakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_belumpunyakunMouseClicked
        dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_belumpunyakunMouseClicked

    private void btLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMouseClicked

    }//GEN-LAST:event_btLoginMouseClicked

    private void jtxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel belumpunyakun;
    private javax.swing.JLabel btExit;
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jtxPassword;
    private javax.swing.JTextField jtxUsername;
    private javax.swing.JLabel judullogin;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel labelusername;
    private javax.swing.JPanel panelhijau;
    private javax.swing.JPanel panelputih;
    // End of variables declaration//GEN-END:variables
}
