/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RequestController;
import javax.swing.JOptionPane;
import model.CurrentUser;
import view.Login;
import view.MenuUserHistory;
import view.MenuUserTentangKami;

/**
 *
 * @author LENOVO
 */
public class MenuUserRequest extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public MenuUserRequest() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        panelputih = new javax.swing.JPanel();
        panelhijau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btTentangKami = new javax.swing.JLabel();
        btBuatRequest = new javax.swing.JLabel();
        btHistory = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        btKiri = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NamaLengkap = new javax.swing.JTextField();
        Organik = new javax.swing.JRadioButton();
        NonOrganik = new javax.swing.JRadioButton();
        Berbahaya = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Kirim = new javax.swing.JButton();
        btKanan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Domisili = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelputih.setBackground(new java.awt.Color(255, 255, 255));

        panelhijau.setBackground(new java.awt.Color(80, 200, 120));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATANG");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon recycle.png"))); // NOI18N

        btTentangKami.setForeground(new java.awt.Color(255, 255, 255));
        btTentangKami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon grub.png"))); // NOI18N
        btTentangKami.setText("Tentang Kami");
        btTentangKami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTentangKamiMouseClicked(evt);
            }
        });

        btBuatRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBuatRequest.setForeground(new java.awt.Color(255, 255, 255));
        btBuatRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon pesawat.png"))); // NOI18N
        btBuatRequest.setText("Buat Request");
        btBuatRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuatRequestMouseClicked(evt);
            }
        });

        btHistory.setForeground(new java.awt.Color(255, 255, 255));
        btHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon history.png"))); // NOI18N
        btHistory.setText("History");
        btHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHistoryMouseClicked(evt);
            }
        });

        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        logout.setText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelhijauLayout = new javax.swing.GroupLayout(panelhijau);
        panelhijau.setLayout(panelhijauLayout);
        panelhijauLayout.setHorizontalGroup(
            panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhijauLayout.createSequentialGroup()
                .addGroup(panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelhijauLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGroup(panelhijauLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel4)))
                    .addGroup(panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btTentangKami)
                        .addComponent(btBuatRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelhijauLayout.setVerticalGroup(
            panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhijauLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(btTentangKami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuatRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btKiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon panah.png"))); // NOI18N
        btKiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKiriMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setText("BUAT REQUEST");

        NamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaLengkapActionPerformed(evt);
            }
        });

        Organik.setText("Organik");
        Organik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganikActionPerformed(evt);
            }
        });

        NonOrganik.setText("NonOrganik");
        NonOrganik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonOrganikActionPerformed(evt);
            }
        });

        Berbahaya.setText("Berbahaya");
        Berbahaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerbahayaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Lengkap");

        jLabel6.setText("Domisili");

        Kirim.setBackground(new java.awt.Color(80, 200, 120));
        Kirim.setForeground(new java.awt.Color(255, 255, 255));
        Kirim.setText("Kirim");
        Kirim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Kirim.setBorderPainted(false);
        Kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirimActionPerformed(evt);
            }
        });

        btKanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon panah kanan.png"))); // NOI18N
        btKanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKananMouseClicked(evt);
            }
        });

        jLabel7.setText("Jenis Sampah");

        Domisili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomisiliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelputihLayout = new javax.swing.GroupLayout(panelputih);
        panelputih.setLayout(panelputihLayout);
        panelputihLayout.setHorizontalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelputihLayout.createSequentialGroup()
                .addComponent(panelhijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelputihLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelputihLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btKiri)
                                    .addGroup(panelputihLayout.createSequentialGroup()
                                        .addComponent(Organik)
                                        .addGap(18, 18, 18)
                                        .addComponent(NonOrganik)
                                        .addGap(18, 18, 18)
                                        .addComponent(Berbahaya)
                                        .addGap(60, 60, 60)
                                        .addComponent(Kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btKanan)))
                        .addGap(17, 17, 17))
                    .addGroup(panelputihLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NamaLengkap, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(Domisili))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        panelputihLayout.setVerticalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelhijau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelputihLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btKiri)
                    .addComponent(btKanan))
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Domisili, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Organik)
                    .addComponent(NonOrganik)
                    .addComponent(Berbahaya)
                    .addComponent(Kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 46, Short.MAX_VALUE))
        );

        getContentPane().add(panelputih, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void btHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHistoryMouseClicked
        dispose();
        new MenuUserHistory().setVisible(true);
    }//GEN-LAST:event_btHistoryMouseClicked

    private void btBuatRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuatRequestMouseClicked
        dispose();
        new MenuUserRequest().setVisible(true);
    }//GEN-LAST:event_btBuatRequestMouseClicked

    private void btTentangKamiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTentangKamiMouseClicked
        dispose();
        new MenuUserTentangKami().setVisible(true);
    }//GEN-LAST:event_btTentangKamiMouseClicked

    private void NamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaLengkapActionPerformed

    private void btKiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKiriMouseClicked
        dispose();
        new MenuUserTentangKami().setVisible(true);
    }//GEN-LAST:event_btKiriMouseClicked

    private void btKananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKananMouseClicked
        dispose();
        new MenuUserHistory().setVisible(true);
    }//GEN-LAST:event_btKananMouseClicked

    private void KirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirimActionPerformed
     String jenisSampah = ""; // Nilai default
    if (Organik.isSelected()) {
        jenisSampah = "1"; // ID Organik
    } else if (NonOrganik.isSelected()) {
        jenisSampah = "2"; // ID NonOrganik
    } else if (Berbahaya.isSelected()) {
        jenisSampah = "3"; // ID Berbahaya
    }

    if (!jenisSampah.isEmpty()) {
        // Ambil user ID dari CurrentUser
        int userId = CurrentUser.getInstance().getIdUser(); 

        // Simpan request ke database
        RequestController requestController = new RequestController();
        boolean isSaved = requestController.saveRequest(userId, jenisSampah);

        if (isSaved) {
            JOptionPane.showMessageDialog(this, "Request berhasil dikirim.");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengirim request.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih jenis sampah terlebih dahulu!");
    }
    }//GEN-LAST:event_KirimActionPerformed

    private void OrganikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrganikActionPerformed

    private void NonOrganikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonOrganikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NonOrganikActionPerformed

    private void BerbahayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerbahayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BerbahayaActionPerformed

    private void DomisiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomisiliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DomisiliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUserRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Berbahaya;
    private javax.swing.JTextField Domisili;
    private javax.swing.JButton Kirim;
    private javax.swing.JTextField NamaLengkap;
    private javax.swing.JRadioButton NonOrganik;
    private javax.swing.JRadioButton Organik;
    private javax.swing.JLabel btBuatRequest;
    private javax.swing.JLabel btHistory;
    private javax.swing.JLabel btKanan;
    private javax.swing.JLabel btKiri;
    private javax.swing.JLabel btTentangKami;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panelhijau;
    private javax.swing.JPanel panelputih;
    // End of variables declaration//GEN-END:variables
}
