/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import controller.RequestController;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Database;

/**
 *
 * @author LENOVO
 */
public class MenuUserHistory extends javax.swing.JFrame {
     
    private Database database;
    private RequestController requestController;
   
    
    
    /**
     * Creates new form MenuUser
     */
    public MenuUserHistory() {
        initComponents();
        requestController = new RequestController();
        loadRequestData();
        setLocationRelativeTo(null);
        DefaultTableModel tableModel = (DefaultTableModel) HistoryRequest.getModel();
    }
    
    private void hideIdRequestColumn() {
    // Ambil model kolom dari tabel
    HistoryRequest.getColumnModel().getColumn(0).setMinWidth(0);
    HistoryRequest.getColumnModel().getColumn(0).setMaxWidth(0);
    HistoryRequest.getColumnModel().getColumn(0).setWidth(0);
}
    private void loadRequestData() {
    // Buat model tabel dengan header kolom yang benar
    DefaultTableModel tableModel = (DefaultTableModel) HistoryRequest.getModel();
    
    HistoryRequest.setModel(tableModel); // Set model tabel
    // Kosongkan tabel (jika diperlukan)
    tableModel.setRowCount(0);
    
    // Muat data dari database
    requestController.loadRequestsHistory(tableModel);
    hideIdRequestColumn();
}

    RequestController urs = new RequestController().updateRequestStatusInDatabase(HEIGHT, newStatus);


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelputih = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btTentangKami = new javax.swing.JLabel();
        btBuatRequest = new javax.swing.JLabel();
        btHistory = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btKiri = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryRequest = new javax.swing.JTable();
        Cancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelputih.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(80, 200, 120));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATANG");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon recycle.png"))); // NOI18N

        btTentangKami.setForeground(new java.awt.Color(255, 255, 255));
        btTentangKami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon grub.png"))); // NOI18N
        btTentangKami.setText("Tentang Kami");
        btTentangKami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTentangKamiMouseClicked(evt);
            }
        });

        btBuatRequest.setForeground(new java.awt.Color(255, 255, 255));
        btBuatRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon pesawat.png"))); // NOI18N
        btBuatRequest.setText("Buat Request");
        btBuatRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuatRequestMouseClicked(evt);
            }
        });

        btHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHistory.setForeground(new java.awt.Color(255, 255, 255));
        btHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon history.png"))); // NOI18N
        btHistory.setText("History");
        btHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHistoryMouseClicked(evt);
            }
        });

        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        logout.setText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btTentangKami)
                        .addComponent(btBuatRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(btTentangKami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuatRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setText("HISTORY REQUEST");

        btKiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon panah.png"))); // NOI18N
        btKiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKiriMouseClicked(evt);
            }
        });

        HistoryRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Request ", "Jenis Sampah", "Jam Request", "Jam Jemput", "Status", "Estimasi", "Kru Penjemput"
            }
        ));
        jScrollPane1.setViewportView(HistoryRequest);

        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelputihLayout = new javax.swing.GroupLayout(panelputih);
        panelputih.setLayout(panelputihLayout);
        panelputihLayout.setHorizontalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelputihLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelputihLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btKiri))
                        .addGap(29, 29, 29))
                    .addGroup(panelputihLayout.createSequentialGroup()
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel16))
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelputihLayout.setVerticalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelputihLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btKiri)
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelputih, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void btTentangKamiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTentangKamiMouseClicked
        dispose();
        new MenuUserTentangKami().setVisible(true);
    }//GEN-LAST:event_btTentangKamiMouseClicked

    private void btHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHistoryMouseClicked
        dispose();
        new MenuUserHistory().setVisible(true);
    }//GEN-LAST:event_btHistoryMouseClicked

    private void btKiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKiriMouseClicked
        dispose();
        new MenuUserRequest().setVisible(true);
    }//GEN-LAST:event_btKiriMouseClicked

    private void btBuatRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuatRequestMouseClicked
        dispose();
        new MenuUserRequest().setVisible(true);
    }//GEN-LAST:event_btBuatRequestMouseClicked

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
     DefaultTableModel tableModel = (DefaultTableModel) HistoryRequest.getModel();

    // Dapatkan baris yang sedang dipilih
    int selectedRow = HistoryRequest.getSelectedRow();

    if (selectedRow != -1) { // Pastikan ada baris yang dipilih
        String status = tableModel.getValueAt(selectedRow, 4).toString(); // Kolom Status (sesuai dengan indeks kolom tabel)
        int requestId = Integer.parseInt(tableModel.getValueAt(selectedRow, 0).toString()); // Kolom ID Request

        if ("PENDING".equalsIgnoreCase(status)) {
            // Ubah status di database dan di tabel
            updateRequestStatusInDatabase(requestId, "CANCEL");
            tableModel.setValueAt("CANCEL", selectedRow, 4);

            JOptionPane.showMessageDialog(this, "Status berhasil diubah menjadi CANCEL.");
        } else {
            JOptionPane.showMessageDialog(this, "Hanya dapat membatalkan request dengan status PENDING.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih baris terlebih dahulu.");
    }




    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUserHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUserHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUserHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUserHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUserHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cancel;
    private javax.swing.JTable HistoryRequest;
    private javax.swing.JLabel btBuatRequest;
    private javax.swing.JLabel btHistory;
    private javax.swing.JLabel btKiri;
    private javax.swing.JLabel btTentangKami;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panelputih;
    // End of variables declaration//GEN-END:variables
}
