/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Database;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Regis;
/**
 *
 * @author LENOVO
 */
public class Register extends javax.swing.JFrame {
    
    /**
     * Creates new form Regis
     */
    public Register() {
    initComponents();
    setLocationRelativeTo(null);
    
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelputih = new javax.swing.JPanel();
        panelhijau = new javax.swing.JPanel();
        labelregister = new javax.swing.JLabel();
        labelexit = new javax.swing.JLabel();
        iconuser = new javax.swing.JLabel();
        labelusername = new javax.swing.JLabel();
        jtxUsername = new javax.swing.JTextField();
        jtxPassword = new javax.swing.JTextField();
        jtxKontak = new javax.swing.JTextField();
        jtxDomisili = new javax.swing.JTextField();
        btKirim = new javax.swing.JButton();
        labelpassword = new javax.swing.JLabel();
        labelemail = new javax.swing.JLabel();
        labeldomisili = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxNamalengkap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelputih.setBackground(new java.awt.Color(255, 255, 255));

        panelhijau.setBackground(new java.awt.Color(80, 200, 120));

        labelregister.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        labelregister.setForeground(new java.awt.Color(255, 255, 255));
        labelregister.setText("REGISTER");

        labelexit.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        labelexit.setForeground(new java.awt.Color(255, 255, 255));
        labelexit.setText("EXIT");
        labelexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelexitMouseClicked(evt);
            }
        });

        iconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon users.png"))); // NOI18N
        iconuser.setToolTipText("");

        javax.swing.GroupLayout panelhijauLayout = new javax.swing.GroupLayout(panelhijau);
        panelhijau.setLayout(panelhijauLayout);
        panelhijauLayout.setHorizontalGroup(
            panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhijauLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelregister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(labelexit)
                .addGap(27, 27, 27))
        );
        panelhijauLayout.setVerticalGroup(
            panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhijauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelhijauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelregister)
                    .addComponent(iconuser)
                    .addGroup(panelhijauLayout.createSequentialGroup()
                        .addComponent(labelexit)
                        .addGap(11, 11, 11)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        labelusername.setText("Username");

        jtxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxUsernameActionPerformed(evt);
            }
        });

        jtxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxPasswordActionPerformed(evt);
            }
        });

        jtxKontak.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxKontakInputMethodTextChanged(evt);
            }
        });
        jtxKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxKontakActionPerformed(evt);
            }
        });

        jtxDomisili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxDomisiliActionPerformed(evt);
            }
        });

        btKirim.setBackground(new java.awt.Color(80, 200, 120));
        btKirim.setForeground(new java.awt.Color(255, 255, 255));
        btKirim.setText("Kirim");
        btKirim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btKirim.setBorderPainted(false);
        btKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKirimActionPerformed(evt);
            }
        });

        labelpassword.setText("Password");

        labelemail.setText("Kontak");

        labeldomisili.setText("Domisili");

        jLabel1.setText("Nama Lengkap");

        jtxNamalengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNamalengkapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelputihLayout = new javax.swing.GroupLayout(panelputih);
        panelputih.setLayout(panelputihLayout);
        panelputihLayout.setHorizontalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelputihLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelputihLayout.createSequentialGroup()
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxNamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelusername)
                                .addComponent(labelpassword)
                                .addComponent(jtxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelemail)
                                    .addComponent(labeldomisili, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelputihLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelputihLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(138, 138, 138))
            .addGroup(panelputihLayout.createSequentialGroup()
                .addComponent(panelhijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelputihLayout.setVerticalGroup(
            panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelputihLayout.createSequentialGroup()
                .addComponent(panelhijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelemail)
                    .addComponent(labelusername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpassword)
                    .addComponent(labeldomisili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelputihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxNamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        getContentPane().add(panelputih, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexitMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_labelexitMouseClicked

    private void jtxNamalengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNamalengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNamalengkapActionPerformed

    private void jtxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxPasswordActionPerformed

    private void btKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKirimActionPerformed
        Regis regis = new Regis();
        
        String username = jtxUsername.getText();
        String password = jtxPassword.getText(); // Menggunakan JTextField untuk password
        String fullName = jtxNamalengkap.getText();
        String domisili = jtxDomisili.getText();
        String kontak = jtxKontak.getText();

        if (username.isEmpty() || password.isEmpty() || fullName.isEmpty() || domisili.isEmpty() || kontak.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = regis.register(username, password, fullName, domisili, kontak);
        if (success) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil!", "Registrasi Berhasil", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new Login().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat registrasi.", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_btKirimActionPerformed

    private void jtxKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxKontakActionPerformed

    private void jtxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxUsernameActionPerformed

    private void jtxDomisiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxDomisiliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDomisiliActionPerformed

    private void jtxKontakInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxKontakInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxKontakInputMethodTextChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKirim;
    private javax.swing.JLabel iconuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtxDomisili;
    private javax.swing.JTextField jtxKontak;
    private javax.swing.JTextField jtxNamalengkap;
    private javax.swing.JTextField jtxPassword;
    private javax.swing.JTextField jtxUsername;
    private javax.swing.JLabel labeldomisili;
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labelexit;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel labelregister;
    private javax.swing.JLabel labelusername;
    private javax.swing.JPanel panelhijau;
    private javax.swing.JPanel panelputih;
    // End of variables declaration//GEN-END:variables
}
